# Generated by Django 4.2.11 on 2024-05-08 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='time which this object was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='time which this object was modified')),
                ('name', models.CharField(help_text='نام برچسب', max_length=10, verbose_name='نام')),
                ('accept', models.BooleanField(default=False, verbose_name='تایید شده')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='time which this object was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='time which this object was modified')),
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField()),
                ('preview', models.CharField(blank=True, max_length=150, null=True, verbose_name='پیشن نمایش')),
                ('text', models.TextField(verbose_name='متن داستان')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
                ('accept', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('tags', models.ManyToManyField(blank=True, to='story.tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'داستان',
                'verbose_name_plural': 'داستان ها',
            },
        ),
    ]
